CC=g++
CFLAGS+=-Wall -O0 -std=c++17 -g -D_GLIBCXX_USE_NANOSLEEP -I../asio/asio/include
LFLAGS=-pthread 
VPATH=../src/:./src/

%.o : %.cxx
	$(CC) $(CFLAGS) -c -o $@ $<

OBJS=test_async_result.o test_strfmt.o test_runner.o buffer.o snapshot.o snapshot_sync_req.o srv_config.o cluster_config.o test_buffer.o test_serialization.o raft_server.o peer.o test_impls.o asio_service.o test_logger.o test_scheduler.o ../src/fs_log_store.o test_log_store.o test_ptr.o test_everything_together.o

testr: $(OBJS)
	$(CC) -o $@ $^ -Wl,--no-as-needed $(LFLAGS)
	@-rm -rf debug
	@-mkdir debug
	@-mv *.o debug/
	@-mv ../src/fs_log_store.o debug/
	@-mv $@ debug/

clean:
	@-rm -rf debug
